export const CONTENT_TEMPLATES = {
  pillar: {
    name: "Pillar Content",
    template: {
      structure: [
        "Introduction: Overview of the issue",
        "Basic definitions and concepts",
        "In-depth analysis:",
        "  - Part 1: {Aspect 1}",
        "  - Part 2: {Aspect 2}",
        "  - Part 3: {Aspect 3}",
        "Best practices and tips",
        "Common problems and solutions",
        "Case studies/real examples",
        "FAQ",
        "Additional resources",
        "Conclusion",
      ],
      optimization: [
        "Use a clear hierarchical structure with H1, H2, H3 headers",
        "Include a table of contents for easy navigation",
        "Target primary keywords in headers and first 200 words",
        "Add internal links to supporting content",
        "Optimize readability with short paragraphs and bullet points",
        "Include expert quotes or statistics for credibility",
        "Update regularly to maintain freshness",
        "Add schema markup for better SERP visibility",
        "Include downloadable resources (checklists, templates)",
        "Aim for 3000+ words but focus on comprehensiveness",
      ],
    },
  },
  supporting: {
    name: "Supporting Content",
    template: {
      structure: [
        "Brief topic introduction",
        "Why this matters",
        "Step-by-step guide:",
        "  - Step 1: {Details}",
        "  - Step 2: {Details}",
        "  - Step 3: {Details}",
        "Tips and notes",
        "Conclusion",
        "Links to related pillar content",
      ],
      optimization: [
        "Target long-tail keywords related to pillar content",
        "Use LSI keywords throughout the content",
        "Create strong internal linking structure",
        "Include practical examples and screenshots",
        "Keep paragraphs under 3-4 sentences",
        "Use descriptive subheadings for scannability",
        "Add relevant images every 300-400 words",
        "Include expert tips or insider knowledge",
        "Link to authoritative external sources",
        "End with clear next steps or related articles",
      ],
    },
  },
  informational: {
    name: "Informational Content",
    template: {
      structure: [
        "Reader's pain point",
        "Overview solution",
        "Specific implementation steps",
        "Illustrative examples",
        "Common mistakes to avoid",
        "Summary",
        "CTA (Call to Action)",
      ],
      optimization: [
        "Focus on featured snippet optimization",
        "Use question-based headers (How, What, Why)",
        "Include step-by-step instructions",
        "Add numbered lists for processes",
        "Use descriptive meta descriptions",
        "Include FAQ section targeting related queries",
        "Add video or visual aids where relevant",
        "Use data and statistics to support points",
        "Include expert opinions or quotes",
        "Optimize for voice search queries",
      ],
    },
  },
  commercial: {
    name: "Commercial Content",
    template: {
      structure: [
        "Product/service overview",
        "Key features",
        "Pros",
        "Cons",
        "Pricing and options",
        "User reviews",
        "Verdict and recommendations",
        "Comparison table",
        "Buying guide",
      ],
      optimization: [
        "Use comparison tables for features/pricing",
        "Include real user testimonials",
        "Add high-quality product images",
        "Include pros and cons lists",
        "Use star ratings and review schemas",
        "Add price comparison tools",
        "Include affiliate disclosure when needed",
        "Update pricing and availability regularly",
        "Add buyer's journey consideration points",
        "Include decision-making criteria",
      ],
    },
  },
  engagement: {
    name: "Engagement Content",
    template: {
      structure: [
        "Attention-grabbing hook",
        "Problem statement",
        "Different viewpoints",
        "Analysis and argumentation",
        "Real-world examples",
        "Discussion invitation",
        "Open questions for readers",
      ],
      optimization: [
        "Use emotional triggers in headlines",
        "Include controversial or debatable points",
        "Add social share buttons strategically",
        "Use storytelling elements",
        "Include questions throughout content",
        "Add polls or surveys",
        "Use relatable examples",
        "Include call-to-actions for comments",
        "Add click-to-tweet quotes",
        "Use multimedia elements",
      ],
    },
  },
  news: {
    name: "News/Updates",
    template: {
      structure: [
        "Main news summary",
        "Background context",
        "Event details",
        "Industry impact",
        "Expert opinions",
        "Next steps/Predictions",
        "Resources & References",
      ],
      optimization: [
        "Include breaking news schema",
        "Use time stamps and update logs",
        "Add expert commentary",
        "Link to original sources",
        "Use news-specific keywords",
        "Include social proof elements",
        "Add trending hashtags",
        "Use newsworthy statistics",
        "Include industry impact analysis",
        "Add future implications section",
      ],
    },
  },
};

export const CROSS_CONTENT_OPTIMIZATION = {
  mobile: ["Make buttons/links touch-friendly"],
  userExperience: [
    "Include clear CTAs",
    "Use white space effectively",
    "Ensure fast loading times",
    "Make content easily shareable",
    "Include progress indicators for long content",
  ],
};
